# Generated by Django 4.0.4 on 2022-04-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_endorsement'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsement',
            name='approve',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
