# Generated by Django 4.0.4 on 2022-04-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_read',
        ),
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
